### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by 385628424** [Anning01/ComicTweets#2]
-----------开始请求API2D-----------
Traceback (most recent call last):
  File "D:\projects\ai小说\ComicTweets-main\main.py", line 102, in <module>
    asyncio.run(main())
  File "C:\Users\j2eejb\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\j2eejb\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\j2eejb\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\projects\ai小说\ComicTweets-main\main.py", line 84, in main
    await generate_prompt(path, path, name)
  File "D:\projects\ai小说\ComicTweets-main\prompt.py", line 135, in generate_prompt
    await process_line(line, line_number, prompt_json_save_path, messages_save_path, name)
  File "D:\projects\ai小说\ComicTweets-main\prompt.py", line 89, in process_line
    result, message, total_tokens = await Main().prompt_generation_chatgpt(text, messages)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by Anning01** [comment]
Pull latest code
